# Generated by Django 5.0 on 2025-11-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_starredmessage_typingstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("midnight", "Midnight Blue"),
                    ("forest", "Forest Green"),
                    ("sunset", "Sunset Orange"),
                    ("ocean", "Ocean Teal"),
                    ("lavender", "Lavender Purple"),
                    ("rose", "Rose Pink"),
                    ("charcoal", "Charcoal"),
                    ("nord", "Nord"),
                ],
                default="light",
                max_length=20,
            ),
        ),
    ]
