# Generated by Django 5.0 on 2025-11-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_add_theme_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="text_position",
            field=models.CharField(
                choices=[("top", "Top"), ("center", "Center"), ("bottom", "Bottom")],
                default="center",
                max_length=10,
            ),
        ),
    ]
