# Generated by Django 5.0 on 2025-12-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_postreport_savedpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("midnight", "Midnight"),
                    ("amoled", "AMOLED Black"),
                    ("dracula", "Dracula"),
                    ("nord", "Nord"),
                    ("tokyo_night", "Tokyo Night"),
                    ("synthwave", "Synthwave"),
                    ("cyberpunk", "Cyberpunk"),
                    ("forest", "Forest"),
                    ("ocean", "Ocean"),
                    ("sunset", "Sunset"),
                    ("aurora", "Aurora"),
                    ("desert", "Desert"),
                    ("lavender", "Lavender"),
                    ("rose", "Rose"),
                    ("mint", "Mint"),
                    ("peach", "Peach"),
                    ("sky", "Sky"),
                    ("charcoal", "Charcoal"),
                    ("slate", "Slate"),
                    ("graphite", "Graphite"),
                    ("mocha", "Mocha"),
                    ("neon", "Neon"),
                    ("coral", "Coral"),
                    ("emerald", "Emerald"),
                    ("sapphire", "Sapphire"),
                    ("amber", "Amber"),
                ],
                default="light",
                max_length=20,
            ),
        ),
    ]
