# Generated by GitHub Copilot on 2025-12-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_merge_20251219_1935"),
        ("chat", "0011_alter_postreport_reason"),
    ]

    operations = []
