# Generated by Django 5.0 on 2025-12-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_merge_20251220_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('midnight', 'Midnight Blue'), ('forest', 'Forest Green'), ('sunset', 'Sunset Orange'), ('ocean', 'Ocean Teal'), ('lavender', 'Lavender Purple'), ('rose', 'Rose Pink'), ('charcoal', 'Charcoal'), ('nord', 'Nord')], default='light', max_length=20),
        ),
    ]
